export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const REGITSER_SUCCESS = 'REGITSER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'SET_ALERT'

export const UPDATE_LOGIN = 'UPDATE_LOGIN'
export const UPDATE_SIGNUP = 'UPDATE_SIGNUP'


